"""archie-shared — shared types, events, and config for archie-nexus."""

from archie_shared.config import ConfigError, home_dir, load_config
from archie_shared.events import (
    PROTOCOL_VERSION,
    ClientCommand,
    InterruptCommand,
    MessageCommand,
    ServerEvent,
    SessionInfo,
    TextDelta,
    ToolCall,
    ToolResult,
    TurnComplete,
    TurnError,
    TurnInterrupted,
    Usage,
    deserialize_command,
    deserialize_event,
    serialize_command,
    serialize_event,
)
from archie_shared.models import (
    BedrockProvider,
    CostConfig,
    ModelEntry,
    OllamaProvider,
    ProviderConfig,
    calculate_cost,
    get_model,
    load_models,
    provider_name,
)
from archie_shared.schemas import (
    AgentConfig,
    CliConfig,
    GlobalConfig,
    NexusConfig,
    OrchestratorConfig,
    OrchestratorProfile,
    WebConfig,
    expand_workspace_root,
    get_profile,
    load_nexus_config,
)
from archie_shared.types import ContentBlock, TextBlock, ToolResultBlock, ToolUseBlock

__all__ = [
    "AgentConfig",
    "BedrockProvider",
    "ClientCommand",
    "CliConfig",
    "ConfigError",
    "ContentBlock",
    "CostConfig",
    "GlobalConfig",
    "InterruptCommand",
    "MessageCommand",
    "ModelEntry",
    "NexusConfig",
    "OllamaProvider",
    "OrchestratorConfig",
    "OrchestratorProfile",
    "PROTOCOL_VERSION",
    "ProviderConfig",
    "ServerEvent",
    "SessionInfo",
    "TextBlock",
    "TextDelta",
    "ToolCall",
    "ToolResult",
    "ToolResultBlock",
    "ToolUseBlock",
    "TurnComplete",
    "TurnError",
    "TurnInterrupted",
    "Usage",
    "WebConfig",
    "calculate_cost",
    "deserialize_command",
    "deserialize_event",
    "expand_workspace_root",
    "get_model",
    "get_profile",
    "home_dir",
    "load_config",
    "load_models",
    "load_nexus_config",
    "provider_name",
    "serialize_command",
    "serialize_event",
]
