"""Content block types — the building blocks of conversation turns.

A single turn (user or assistant message) can contain multiple blocks.
For example, an assistant response might be [TextBlock, ToolUseBlock, ToolUseBlock]
when the model generates text and then calls two tools.

These types are PROVIDER-AGNOSTIC — they don't know about Bedrock's wire format.
The LLM client translates between these and the provider's format.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class TextBlock:
    """A block of text content.

    In a user message: what the user typed.
    In an assistant message: what the model generated.
    """

    text: str


@dataclass(frozen=True)
class ToolUseBlock:
    """The model wants to call a tool.

    Generated by the model (appears in assistant messages).
    The tool_use_id is generated by the provider and must be propagated to the
    corresponding ToolResultBlock so the model can match results to requests.
    """

    tool_use_id: str
    name: str
    input: dict


@dataclass(frozen=True)
class ToolResultBlock:
    """The result of executing a tool.

    Generated by the agent loop after running a tool handler.
    Appears in a separate "user" turn (that's how Bedrock's protocol works —
    tool results are sent as user messages with toolResult content blocks).
    """

    tool_use_id: str
    content: str
    is_error: bool = False


# Union type for all content blocks.
type ContentBlock = TextBlock | ToolUseBlock | ToolResultBlock
